### ISSUE TITLE
/partners#show: Display categories and products

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/hdffa-directory#60]

**Comment by KristenOrue** [comment]
@Marji712 
After some research on solving this issue: I believe we have to edit a combination of files: 
show.html.haml (The view for when a user clicks into a category) and possibly the categories controller. This link was helpful in solving a similar issue:

https://stackoverflow.com/questions/49703957/rails-display-related-or-similar-posts-from-category-on-the-post-show-page

However, was written in erb so I found a HAML converter for convenience: 

https://awsm-tools.com/code/html2haml

In case the answers you find are in erb. Continuing to research this issue and for now asses the word "Partners" to the view.

**Comment by KristenOrue** [comment]
Some additional discoveries: 

I was trying to use: 
```Partner.where(category_id: @category.id).each do |partner|```
within the categories show.html.haml file and the reason it wasn't working is after checking the schema.rb,
Partners table doesn't have a category_id : ) 

But there is a categorys_partners table that does relate the category_id to the partner_id. I assume this was created to have a one to many relationship instead of many to many?

Pseudo-code thoughts on fixing this situation:
Go into category_partners and find all the partners_id that correlate with category_id. For each partner_id: print partner partner.name. 

My final question is: Do we need to create a category_partner model in order to access the database? Which I assume we do since that's what the model does.

**Comment by Marji712** [comment]
@KristenOrue It looks like the partners show.html.haml shows the "categories", but calls them Keywords (and has some format issues). Is keywords an artifact we should be getting rid of? 
I see the categories_partners table you're talking about. I'll try and step through that pseudo code and see if I can get something working.

**Comment by Marji712** [comment]
updated the haml to:
`%dt.col-sm-3 Categories
      %dd.col-sm-9
        - @partner.categories.each do |category|
          .row= category.name 
      %dt.col-sm-3 Products
      %dd.col-sm-9
        - @partner.products.each do |product|
          .row= product.name`
