### ISSUE TITLE
lib/tasks/db.rake:category from json to objects

### ISSUE THREAD

**Issue by Marji712** [osu-cascades/hdffa-directory#67]

**Comment by KristenOrue** [comment]
Added:
`category_name = val['Category']
      unless category_name.blank?
        category = Category.find_or_create_by(name: category_name)
        category.partners << partner
      end`
to db.rake file so that categories are now imported. 

I had to run `rails db:reset` before running `rails db:import_partners` to prove that it worked on my localhost:3000

Then I had to run those commands within the staging server: 
`heroku pg:reset -rstaging`
Then recreate the tables:
`heroku run rails db:migrate -rstaging`
Then import the data:
`heroku run rake db:import_partners -rstaging`

Then since this will kill all the existing user data too I had to recreate my user:
`User.create(first_name: 'Kristen', last_name: 'Orue', email: 'oruek@oregonstate.edu', password: 'password', role: 'admin')`
